---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-drivers
{{ include "charts.labels.standard" .}}
  name: cloud-drivers
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.global.ports.cloud_drivers }}
    targetPort: "http"
  selector:
    app: cloud-drivers
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
