sed -e "s/9123/{{.Values.gatekeeper.port}}/" \
	-e "s/8000/{{.Values.hakken.port}}/g" \
	-e "s/9191/{{.Values.highwater.port}}/g" \
	-e "s/9157/{{.Values.hydrophone.port}}/g" \
	-e "s/9122/{{.Values.jellyfish.port}}/g" \
	-e "s/9119/{{.Values.message.api.port}}/g" \
	-e "s/9222/{{.Values.platform.auth.port}}/g" \
	-e "s/9225/{{.Values.platform.blob.port}}/g" \
	-e "s/9220/{{.Values.platform.data.port}}/g" \
	-e "s/9223/{{.Values.platform.notification.port}}/g" \
	-e "s/9224/{{.Values.platform.task.port}}/g" \
	-e "s/9221/{{.Values.platform.user.port}}/g" \
	-e "s/9120/{{.Values.seagull.port}}/g" \
	-e "s/9107/{{.Values.shoreline.port}}/g" \
	-e "s/8009/{{.Values.styx.port}}/g" \
	-e "s/9127/{{.Values.tide.whisperer.port}}/g" \
	-e "s/9300/{{.Values.tide.export.port}}/g" \
	-e "s/3000/{{.Values.blip.port}}/g" 
