{{ if .Values.secret.enabled -}}
---
apiVersion: v1
{{ with .Values.secret.data_ -}}
data:
  UserClientId: {{ .UserClientId | default "" | b64enc | quote }}
  UserClientSecret: {{ .UserClientSecret | default "" | b64enc | quote }}
  ServiceClientId: {{ .ServiceClientId | default "" | b64enc | quote }}
  ServiceClientSecret: {{ .ServiceClientSecret | default "" | b64enc | quote }}
  StateSalt: {{ .StateSalt | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: tandem
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
