#!/bin/bash 
#
# combine independent yaml/json files in directory and all subdirectories together
# File names and directory names are ignored.
#
# Usage: $0 ${file}|${directory} ${initialValue:-"{}"}
#

ARGS=$(jsonnet_path)

input=${1:-.}
result=${2:-"{}"}
files=$(find $input -name \*.yaml -print)
files="$files $(find $input -name \*.json -print)"
for file in $files
do
	result=$(jsonnet $ARGS \
	--tla-code input="$(yq read $file -j)" \
	--tla-code result="$result" \
	lib/merge.jsonnet)
done
echo $result
