#!/bin/bash 
#
# Create Manifests from input directory.
# Use defaults in defaults directory.

for x in kubernetes cf eksctl
do
  if [ $# == 1 ]
  then
      combined=$(combine $1 "default")
  else
      combined=$(combine default)
  fi
  
  sjsonnet  --tla-code config="$combined" $x.jsonnet >$x.out
done
