#!/bin/bash
#
# Create Manifests from input directory.
# Use defaults in defaults directory.

default=$(combine default)
if [ $# == 1 ]
then
    jsonnet  --tla-code-file config=<(combine $1 "$default") all.jsonnet
else
    jsonnet  --tla-code config="${default}" all.jsonnet
fi
