# -- whether to enable Keycloak integration
enabled: true
keycloakx:
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
    - "--import-realm"
  extraEnv: |-
    - "name": "KEYCLOAK_ADMIN"
      "value": "admin"
    - "name": "KEYCLOAK_ADMIN_PASSWORD"
      "value": "admin"
    - "name": "KC_FEATURES"
      "value": "admin-fine-grained-authz,token-exchange,admin"
    - "name": "KC_HOSTNAME_URL"
      "value": "http://localhost:32000"
    - "name": "KC_HOSTNAME_ADMIN_URL"
      "value": "http://localhost:32000"
    - "name": "KC_HOSTNAME_STRICT"
      "value": "false"
    - "name": "KC_PROXY"
      "value": "edge"
    - "name": "KC_SPI_STICKY_SESSION_ENCODER_INFINISPAN_SHOULD_ATTACH_ROUTE"
      "value": "false"
    - "name": "KC_HTTP_ENABLED"
      "value": "true"
    - "name": "KC_HOSTNAME_STRICT_HTTPS"
      "value": "false"
    - "name": "KC_CACHE"
      "value": "local"
    - "name": "KC_LOG_CONSOLE_OUTPUT"
      "value": "json"
    - "name": "KC_LOG_LEVEL"
      "value": "INFO,org.keycloak.services.IdentityBrokerService:DEBUG,org.keycloak.saml:DEBUG"
    - "name": "DISABLE_EXTERNAL_ACCESS"
      "value": "false"
    - "name": "TIDEPOOL_ASSETS_URL"
      "value": "https://s3-us-west-2.amazonaws.com/tidepool-prd-asset"
  extraInitContainers: |-
    - "command":
      - "/bin/sh"
      - "-c"
      - "cp /release/extensions/*.jar /providers && cp -R /release/tidepool-theme/* /tidepool"
      "image": "docker.io/tidepool/keycloak-extensions:21.1.1-2024-03-01T00-00-00"
      "imagePullPolicy": "IfNotPresent"
      "name": "tidepool-extensions"
      "volumeMounts":
      - "mountPath": "/providers"
        "name": "providers"
      - "mountPath": "/tidepool"
        "name": "tidepool-theme"
  extraVolumeMounts: |-
    - "mountPath": "/opt/keycloak/providers"
      "name": "providers"
    - "mountPath": "/opt/keycloak/themes/tidepool"
      "name": "tidepool-theme"
    - "mountPath": "/opt/keycloak/data/import"
      "name": "keycloak-import"
      "readOnly": true
  extraVolumes: |-
    - "emptyDir": {}
      "name": "providers"
    - "emptyDir": {}
      "name": "tidepool-theme"
    - "emptyDir": {}
      "name": "db"
    - "secret":
        "secretName": "keycloak-realm"
      "name": "keycloak-import"
  fullnameOverride: keycloak
  http:
    relativePath: /
  image:
    repository: quay.io/keycloak/keycloak
    tag: 21.1.1
  livenessProbe: |-
    "httpGet":
      "path": "/health/live"
      "port": "http"
    "initialDelaySeconds": 600
    "timeoutSeconds": 20
