{{ if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oura
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "charts.labels.standard" . }}
data:
{{ if .Values.configmap.acceptURL }}
  AcceptURL: "{{ .Values.configmap.acceptURL }}"
{{ else }}
  AcceptURL: "{{include "charts.host.app" .}}/oauth/oura/accept"
{{ end }}
  AuthorizeURL: "{{ .Values.configmap.authorizeURL | default "https://cloud.ouraring.com/oauth/authorize?prompt=login" }}"
{{ if .Values.configmap.redirectURL }}
  RedirectURL: "{{ .Values.configmap.redirectURL }}"
{{ else }}
  RedirectURL: "{{include "charts.host.api" .}}/v1/oauth/oura/redirect"
{{ end }}
  TokenURL: "{{ .Values.configmap.tokenURL | default "https://api.ouraring.com/oauth/token" }}"
  RevokeURL: "{{ .Values.configmap.revokeURL | default "https://api.ouraring.com/oauth/revoke" }}"
  Scopes: "{{ .Values.configmap.scopes | default "" }}"
  ClientURL: "{{ .Values.configmap.clientURL | default "https://api.ouraring.com" }}"
{{ if .Values.configmap.partnerURL }}
  PartnerURL: "{{ .Values.configmap.partnerURL }}"
{{ else }}
  PartnerURL: "{{include "charts.host.api" .}}/v1/partners/oura"
{{ end }}
{{ if .Values.configmap.jotformBaseURL }}
  JotformBaseURL: "{{ .Values.configmap.jotformBaseURL }}"
{{ end }}
  JotformEnabled: "{{ .Values.configmap.jotformEnabled }}"
  JotformFormId: "{{ .Values.configmap.jotformFormId | default "" }}"
  JotformTeamId: "{{ .Values.configmap.jotformTeamId | default "" }}"
  ShopifyEnabled: "{{ .Values.configmap.shopifyEnabled }}"
  ShopifyStoreId: "{{ .Values.configmap.shopifyStoreId | default "" }}"
{{ end }}
