deployment:
  # -- secrets used to pull images
  imagePullSecrets:
  image: tidepool/plotly-orca:latest
  replicas: 1

# -- memory and cpu resources for pods
resources:
  requests:
    memory: "700Mi"
